server:
  port: 8010

spring:
  kafka:
    bootstrap-servers: fwfurtado-host.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name: books